version: "3"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goreactstudy
    ports:
      - 1323:1323
    volumes:
      - .:/myapp
    working_dir: /myapp
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
networks:
  lesson:


