version: "3"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goreactstudy
    volumes:
      - .:/myapp
      - $SSH_AUTH_SOCK:/ssh-agent
    working_dir: /myapp
    command: /bin/sh -c "eval $(ssh-agent -s) && while sleep 1000; do :; done"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    networks:
      - lesson

  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: udemy
      POSTGRES_PASSWORD: udemy
      POSTGRES_DB: udemy
    restart: always
    networks:
      - lesson

networks:
  lesson: